### ISSUE TITLE
Dismounter does not dismount upon certain spell casts

### ISSUE THREAD

**Issue by KevinTyrrell** [jb-dijkstra/dismounter#1]
Dismounter does not dismount the player if they perform an action that cannot be successfully casted. For example

* Fireball when the target is too far away
* Blizzard when the player does not have enough mana
* Intercept when the player does not have any rage

This functionality leads to situations where say, a mounted warrior is running at an enemy, they put the warrior in combat, and the warrior intuitively presses mortal strike to dismount but dismounter does not dismount them because he has insufficient rage.

**Comment by jb-dijkstra** [comment]
I do agree that that in a PVP situation like this you would expect to be dismounted, but for PVE that might not be the expected action. What a solution to this might be is make it an option that you can set, so a slash command for always dismount or not. Do you agree that this would be a solution to this problem?

**Comment by jb-dijkstra** [comment]
No reaction for over a year. So closing the issue.
