### ISSUE TITLE
Does this addon mean to also affect the Druid's forms?

### ISSUE THREAD

**Issue by iDump-ster** [jb-dijkstra/dismounter#2]
Currently when trying to go use a Flight Master when in a form you get a, "You can't take a taxi while shapeshifted!" error.

**Comment by jb-dijkstra** [comment]
It should, I'll mark this as a bug and fix it as soon as I can!

**Comment by jb-dijkstra** [comment]
I'm sad to report that this would never have worked. The problem is a technical limit in the WoW API. I've pushed a new version that removed support for druid forms: https://github.com/jb-dijkstra/dismounter-tbc/releases/tag/2.1.4

**Comment by iDump-ster** [comment]
Oh noooooo!
I tried with a weakaura and it never worked too.
I saw that the error message went away with the addon on, but unfortunately rip. Tried all that you can, appreciate it!
