### ISSUE TITLE
Dismounter TBC

### ISSUE THREAD

**Issue by ailya1988** [jb-dijkstra/dismounter#3]
Dismounter TBC is endlessly trying to update in CurseForge Client.
![Screenshot_1](https://user-images.githubusercontent.com/63604281/119478532-8e790680-bd58-11eb-8ca7-8c5475d89187.png)

**Comment by jb-dijkstra** [comment]
That's a weird bug, I think it might have something to do with the naming of the files. I did just push a new version that should fix this problem. Can you please confirm that the problem is solved?

**Comment by jb-dijkstra** [comment]
As I can't reproduce the problem anymore I'll go ahead and close this issue.
