### ISSUE TITLE
Lua error 

### ISSUE THREAD

**Issue by Paroyer** [jb-dijkstra/dismounter#4]
Happens on my level 31 rogue for some reason, have no idea what cause this:

46x dismounter-tbc\Dismounter_Core.lua:13: attempt to perform arithmetic on a string value
[string "@dismounter-tbc\Dismounter_Core.lua"]:13: in function <dismounter-tbc\Dismounter_Core.lua:8>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "UI_ERROR_MESSAGE"
args = <table> {
 1 = 50
 2 = "Skill not high enough"
}
msg = "Skill not high enough"
(*temporary) = <function> defined @SharedXML\SharedBasicControls.lua:19
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a string value"
addon = <table> {
 core = <table> {
 }
 utils = <table> {
 }
}

**Comment by jb-dijkstra** [comment]
This was a problem with a debug message. I removed them all in version https://github.com/jb-dijkstra/dismounter-tbc/releases/tag/2.1.5
