### ISSUE TITLE
Option to not dismount while flying?

### ISSUE THREAD

**Issue by atraira** [jb-dijkstra/dismounter#5]
I'm sure I'm not the only one accidentally killing myself with this great addon, lol. Would it be possible to add an option to check if you're in the air before dismounting?

**Comment by boktai1000** [comment]
I second this - it's happened twice to me so far. I know some people may want it, but having it behave differently compared to ground mounts has been painful. Maybe an option for preference

**Comment by boktai1000** [comment]
@meowxguy if you're looking for a temporary alternative until this potentially gets added - I'm using Leatrix Plus, which has an option for Dismounting. Ideally of course, Dismounter will allow for this - but I tested multiple addons, and wanted to let it be known just-in-case anyone is looking for something in the interim.

**Comment by jb-dijkstra** [comment]
I'll look into that, I don't know if the API has an option to check for a flying state. I'll come back on this.

**Comment by jb-dijkstra** [comment]
This issue is resolved with version 2.2.0
