### ISSUE TITLE
Update for Wrath and options

### ISSUE THREAD

**Issue by theAnton81** [jb-dijkstra/dismounter#7]
Just a TOC update as it's still working just fine.

It would be nice if we could have some option over which features we want enabled.
Personally I would like to have some options that would stop me from accidentally dismounting at 10k feet. 😄

**Comment by jb-dijkstra** [comment]
@theAnton81 I updated the TOC. There was already an option to prevent dismounting when flying. Check "/dismounter" for the option in game.
